name: Compile and push LaTeX files

on:
  push:
    branches:
        - main
    paths:
      - 'docs/**/*.tex'

concurrency:
  group: ${{ github.ref }}  # Group by branch reference (e.g., 'refs/heads/main')
  cancel-in-progress: true

  
jobs:
  build:
    name: Compile LaTeX files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install LaTeX (pdflatex)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-science

      - name: Compile PDFs
        run: cd docs && make

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Add generated PDF files" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
