name: Check LaTeX files are valid

on:
  pull_request:
    paths:
      - 'docs/**/*.tex'

concurrency:
  group: ${{ github.ref }}  # Group by branch reference (e.g., 'refs/heads/main')
  cancel-in-progress: true

  
jobs:
  build:
    name: Compile LaTeX files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install LaTeX (pdflatex)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-science

      - name: Compile PDFs
        run: cd docs && make

      # if there are no errors, the PDFs should be good to go
