name: Plutos

on:
  push


jobs:
  build:
    name: Build and test Plutos App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LaTeX (pdflatex)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      - name: Compile PDFs
        run: cd docs && make

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: src/client

      - name: Run ESLint
        run: npm run lint
        working-directory: src/client

      # When we start testing we can uncomment this loool
      # - name: Run tests
      #   run: npm test
